package:
  name: python-dateutil
  version: 2.7.2

source:
  url: https://files.pythonhosted.org/packages/c5/39/4da7c2dbc4f023fba5fb2325febcadf0d0ce0efdc8bd12083a0f65d20653/python-dateutil-2.7.2.tar.gz
  md5: 03a08c8bcf0a2b29f1cd21b9de4d12fb

  patches:
    - patches/dummy-thread-lock.patch

test:
  imports:
    - dateutil
